### ISSUE TITLE
Projects left to migrate

### ISSUE THREAD

**Issue by jsignell** [holoviz-topics/examples#23]
I am trying to capture all the projects that I think are still left to migrate, so that I can keep chipping away at them while working on some top-level infrastructure. Please add any that you can think of from other pyviz projects or from your own anaconda.org account. @pyviz-topics/pyviz-dev 

### Already in this repo but not migrated to own project:
- [x] opensky - also need to migrate download script from gist [#26]

geometry:
- [x] lsystems
- [x] square limit

simulation:
- [x] boids
- [x] hipster_dynamics
- [x] sri_model

### From [datashader](https://github.com/pyviz/datashader/blob/master/examples):
- [x] dashboard - should this be a topic or a demo? It is intaked so should it just be its own dir? I think yes.

### From [pyviz-demos](https://github.com/pyviz-demos):
- [ ] bird_migration - also include notebooks in (https://github.com/jsignell/pydata_dc_2018)
- [x] glaciers [#29]
- [x] gapminder - Is this topic-y enough? A (jbednar): Yes, because it's a tricky environment that should be neutralized here. [#29]
- [x] nyc_taxi -> include in nyc_taxi project [#30]
- [x] nyc_taxi-nongeo -> include in nyc_taxi project
- [x] clifford -> include in attractors project [#29]

### From [EarthSim topics](https://github.com/pyviz-topics/EarthSim/blob/master/examples/topics):
- [ ] GrabCut

### From [EarthML](https://github.com/pyviz-topics/EarthML/blob/master/examples/topics):
- [x] Heat_and_Trees [#71]
- [x] Seattle_Lidar

### From anaconda.org/jbednar
- [x] [attractors dashboard](https://anaconda.org/jbednar/project/Attractors) -> include in attractors [#36]
 - [x] [Euler's method](https://anaconda.org/jbednar/eulersmethod)
- [x] [Stock dashboard](https://anaconda.org/jbednar/stock_dashboard/notebook) -- very old, and I think Philipp has a better version, but I think we should have some finance example like that.

**Comment by jbednar** [comment]
> dashboard - should this be a topic or a demo? It is intaked so should it just be its own dir? I think yes.

I still don't know the difference between a topic and a demo, so... yes?

I do think it should be its own directory, but how to get the data without re-downloading it is tricky.

**Comment by Azaya89** [comment]
I think this can be closed now, seeing as almost everything has been ticked.
