### ISSUE TITLE
Clean up issues and PRs

### ISSUE THREAD

**Issue by Azaya89** [holoviz-topics/examples#446]
A tracker for Issues and PRs I plan to close over the next few weeks:

- [x] Closed #271 
- [x] Closed #131 
- [x] #197 closed by @maximlt 
- [x] Closed #23
- [x] Closed #91
- [x] #93 fixed and closed by @maximlt via #457 
- [x] #292 closed by @maximlt 
- [x] Closed #189 via #463 
- [x] #222 closed by @maximlt via #478 
- [x] Closed #178

**Comment by Azaya89** [comment]
I think I can close this now. What do you think @maximlt ?

**Comment by maximlt** [comment]
Yes let's close, thanks!
